export enum RoleEnum {
  ADMINISTRATOR = 'ADMINISTRATOR',
  ADMIN_SIRUP = 'ADMIN_SIRUP',
  ADMIN_PERENCANAAN = 'ADMIN_PERENCANAAN',
  ADMIN_PPK = 'ADMIN_PPK',
  BENDAHARA = 'BENDAHARA',
  KEPALA_OPD = 'KEPALA_OPD',
  PIMPINAN_DAERAH = 'PIMPINAN_DAERAH',
}
